on: push

jobs:
  build:
    name: build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
          - target: x86_64-unknown-linux-musl
          - target: aarch64-unknown-linux-musl
          - target: x86_64-apple-darwin
          - target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@master
      - name: build
        run: |
          pip3 install ziglang
          rustup toolchain install --force-non-host stable-${{ matrix.target }}
          rustup target add ${{ matrix.target }}
          cargo install cargo-zigbuild
          cargo zigbuild --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/nur
